[tool.pytest]
DJANGO_SETTINGS_MODULE = "backend.conf.dev"
python_files = ["tests.py", "test_*.py", "*_tests.py"]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
